"""Catálogo de nichos "dark/faceless" com economia de cada um.

Campos (0-100 salvo indicação):
- rpm_long / rpm_short: RPM em USD por 1000 views para audiência 100% EUA (min, max).
  Multiplica por geo.effective_rpm_mult(lang) para o RPM real esperado.
- competition: saturação de canais faceless no nicho.
- evergreen: quanto o conteúdo continua a render meses/anos depois.
- virality: potencial de explosão em Shorts/TikTok.
- ai_fit: quão bem visuais gerados/stock servem o nicho sem parecer barato.
- clip_fit: quão viável é o modo recorte (fontes CC/licenciáveis abundantes).
- policy_risk: risco de anúncios limitados / desmonetização / strikes.
- complexity: esforço de pesquisa/produção por vídeo.
- best_modes: modos de produção recomendados (ver production/planner.py).

São estimativas de mercado de partida; o módulo de Análise substitui-as pelos teus números reais.
"""
from __future__ import annotations


def N(key, name, category, desc, rpm_long, rpm_short, competition, evergreen, virality, ai_fit, clip_fit,
      policy_risk, complexity, best_modes, audience, pillars, keywords, hooks, subreddits=(), wiki=()):
    return {
        "key": key, "name": name, "category": category, "description": desc,
        "rpm_long": rpm_long, "rpm_short": rpm_short, "competition": competition, "evergreen": evergreen,
        "virality": virality, "ai_fit": ai_fit, "clip_fit": clip_fit, "policy_risk": policy_risk,
        "complexity": complexity, "best_modes": list(best_modes), "audience": audience,
        "pillars": list(pillars), "keywords": list(keywords), "hooks": list(hooks),
        "subreddits": list(subreddits), "wiki_seeds": list(wiki),
    }


NICHES: list[dict] = [
    N("finance_explained", "Finanças & Dinheiro Explicado", "money",
      "Como o dinheiro funciona de verdade: dívidas, bancos, inflação, esquemas dos ricos.",
      (9, 22), (0.12, 0.40), 78, 85, 60, 75, 20, 25, 60,
      ["ai_images_narrated", "stock_narrated"], "Homens 25-44, rendimento médio-alto, EUA/UK/CA",
      ["Como os ricos pensam", "Armadilhas financeiras", "Economia explicada", "Histórias de falência"],
      ["personal finance", "credit score", "inflation", "recession", "wealth", "passive income", "housing market"],
      ["The bank doesn't want you to know this", "Why {X} is quietly making you poor"],
      ["personalfinance", "FluentInFinance", "Economics"], ["Inflation", "Recession", "Federal_Reserve"]),
    N("business_rise_fall", "Ascensão e Queda de Empresas", "money",
      "Estudos de caso dramáticos: como impérios nasceram, fraudaram e colapsaram.",
      (7, 15), (0.08, 0.25), 62, 88, 65, 80, 35, 15, 75,
      ["ai_images_narrated", "stock_narrated", "clip_commentary"], "Homens 18-44, empreendedores, EUA/UK",
      ["Colapsos corporativos", "Fraudes bilionárias", "Estratégias geniais", "Guerras de marcas"],
      ["bankruptcy", "company collapse", "CEO scandal", "fraud", "brand war", "business strategy"],
      ["This company lost $40B in 48 hours", "The genius (and evil) strategy behind {X}"],
      ["business", "Entrepreneur", "wallstreetbets"], ["Enron_scandal", "FTX", "Theranos"]),
    N("ai_tech_explained", "IA & Tecnologia que Assusta", "tech",
      "IA, robôs, vigilância, futuro do trabalho — o lado inquietante da tecnologia.",
      (6, 13), (0.08, 0.25), 70, 55, 80, 90, 40, 15, 55,
      ["ai_images_narrated", "stock_narrated", "clip_commentary"], "Homens 18-40, curiosos de tecnologia, global EN",
      ["IA a tomar decisões", "Vigilância", "Robótica", "Futuro do trabalho"],
      ["artificial intelligence", "AI news", "robots", "surveillance", "AGI", "deepfake"],
      ["This AI just did something it wasn't supposed to", "Nobody is talking about what {X} can do now"],
      ["artificial", "singularity", "technology"], ["Artificial_general_intelligence", "Deepfake"]),
    N("dark_psychology", "Psicologia Sombria", "mind",
      "Manipulação, persuasão, linguagem corporal, narcisismo e comportamento humano.",
      (3, 8), (0.05, 0.15), 85, 90, 85, 80, 10, 20, 35,
      ["ai_images_narrated", "stock_narrated", "text_story"], "Mistura 18-34, autoaperfeiçoamento, EN global",
      ["Manipulação e defesa", "Sinais ocultos", "Narcisismo", "Truques de persuasão"],
      ["dark psychology", "manipulation tactics", "narcissist", "body language", "persuasion"],
      ["If someone does this, they're manipulating you", "3 psychological tricks that feel illegal to know"],
      ["psychology", "NarcissisticAbuse"], ["Dark_triad", "Gaslighting"]),
    N("stoicism_discipline", "Estoicismo & Disciplina", "mind",
      "Filosofia prática, disciplina masculina, sigma/estoico com voz grave e música épica.",
      (2.5, 6), (0.04, 0.12), 90, 92, 80, 85, 15, 10, 25,
      ["ai_images_narrated", "stock_narrated"], "Homens 16-34, EN global",
      ["Lições estoicas", "Disciplina", "Solidão estratégica", "Mentalidade"],
      ["stoicism", "discipline", "marcus aurelius", "self improvement", "motivation"],
      ["Marcus Aurelius warned you about this", "Do this for 30 days and you'll be unrecognizable"],
      ["Stoicism", "selfimprovement"], ["Stoicism", "Marcus_Aurelius"]),
    N("dark_history", "História Sombria", "history",
      "Os capítulos mais perturbadores e desconhecidos da história — sem gore gráfico.",
      (3.5, 8), (0.05, 0.15), 68, 95, 70, 85, 30, 25, 65,
      ["ai_images_narrated", "stock_narrated"], "Homens 25-54, EUA/UK/CA/AU",
      ["Impérios caídos", "Práticas medievais", "Mistérios históricos", "Figuras temidas"],
      ["dark history", "medieval", "ancient rome", "history documentary", "worst jobs in history"],
      ["The most disturbing punishment in history", "Why nobody talks about what happened in {X}"],
      ["history", "AskHistorians", "HistoryPorn"], ["Medieval_warfare", "Roman_Empire"]),
    N("history_for_sleep", "História para Dormir (longo)", "history",
      "Documentários de 1-3h, voz calma, visual lento — tempo de exibição enorme = mid-rolls.",
      (4, 9), (0.03, 0.08), 55, 97, 10, 90, 20, 5, 55,
      ["ai_images_narrated"], "Adultos 25-65, EUA/UK, ouvem a adormecer",
      ["Vida quotidiana no passado", "Civilizações perdidas", "Épocas completas"],
      ["history for sleep", "boring history", "sleep documentary", "medieval life"],
      ["Relax as we explore daily life in {X}"], [], ["Middle_Ages"]),
    N("true_crime", "True Crime", "crime",
      "Casos criminais reais narrados com suspense. Evitar detalhes gráficos p/ manter anúncios.",
      (4, 9), (0.05, 0.15), 80, 80, 75, 60, 45, 60, 70,
      ["stock_narrated", "clip_commentary", "ai_images_narrated"], "Mulheres 25-54, EUA/UK/AU",
      ["Casos resolvidos por detalhe", "Interrogatórios", "Desaparecimentos", "Golpistas"],
      ["true crime", "cold case", "interrogation", "unsolved", "missing person", "scam"],
      ["He thought he got away with it — until this detail", "The 911 call that solved the case"],
      ["TrueCrime", "UnresolvedMysteries"], []),
    N("mysteries_unexplained", "Mistérios & Inexplicável", "mystery",
      "Casos inexplicáveis, lugares proibidos, descobertas estranhas, fenómenos.",
      (2.5, 6), (0.04, 0.12), 75, 85, 85, 90, 30, 25, 50,
      ["ai_images_narrated", "stock_narrated"], "Homens 18-44, EN global",
      ["Lugares proibidos", "Descobertas bizarras", "Sinais misteriosos", "Desaparecimentos"],
      ["unexplained mysteries", "forbidden places", "strange discovery", "ancient mystery"],
      ["Scientists can't explain what they found here", "This place is illegal to visit"],
      ["UnresolvedMysteries", "Glitch_in_the_Matrix"], ["Voynich_manuscript", "Dyatlov_Pass_incident"]),
    N("horror_stories", "Histórias de Terror", "horror",
      "Narrações de terror (creepypasta, relatos 'true scary'), ambiente sonoro forte.",
      (1.8, 4), (0.03, 0.08), 85, 80, 80, 85, 5, 30, 30,
      ["ai_images_narrated", "text_story"], "18-34, EUA/UK, consumo noturno",
      ["Relatos verdadeiros", "Regras de terror", "Lendas urbanas"],
      ["scary stories", "horror stories", "creepypasta", "true scary stories", "rules horror"],
      ["I should never have answered that call at 3AM"], ["nosleep", "LetsNotMeet", "Ghoststories"], []),
    N("space_cosmos", "Espaço & Cosmos Assustador", "science",
      "Escala do universo, ameaças cósmicas, buracos negros, vida extraterrestre.",
      (3.5, 7), (0.05, 0.15), 60, 90, 80, 95, 30, 5, 55,
      ["ai_images_narrated", "stock_narrated", "ai_video_full"], "Homens 16-44, EN global",
      ["Ameaças cósmicas", "Escala", "Missões", "Vida alienígena"],
      ["space", "black hole", "james webb", "universe", "asteroid", "alien life"],
      ["NASA just detected something that shouldn't exist", "What if Earth stopped for 1 second"],
      ["space", "Astronomy"], ["Black_hole", "Fermi_paradox"]),
    N("ocean_deep", "Oceano Profundo", "science",
      "Criaturas abissais, naufrágios, fossas, desastres submarinos — thalassofobia vende.",
      (3, 6.5), (0.04, 0.14), 45, 90, 85, 90, 35, 5, 45,
      ["ai_images_narrated", "stock_narrated", "clip_commentary"], "Homens 18-44, EN global",
      ["Criaturas", "Naufrágios", "Desastres submarinos", "Fossas"],
      ["deep ocean", "mariana trench", "thalassophobia", "shipwreck", "submarine disaster"],
      ["What's really at the bottom of the ocean", "The deepest thing ever found was moving"],
      ["thalassophobia", "oceans"], ["Mariana_Trench", "Titan_submersible_implosion"]),
    N("geopolitics_military", "Geopolítica & Poder Militar", "world",
      "Porque países fazem o que fazem, armamento, conflitos explicados com mapas.",
      (4, 8), (0.05, 0.14), 60, 70, 70, 75, 30, 45, 70,
      ["ai_images_narrated", "stock_narrated"], "Homens 25-54, EUA/UK/DE",
      ["Estratégia de países", "Armamento", "Rotas e recursos", "Cenários 'e se'"],
      ["geopolitics", "military power", "aircraft carrier", "why country", "war explained"],
      ["Why {country} can never be invaded", "The weapon that changed modern war"],
      ["geopolitics", "CredibleDefense"], ["Geopolitics"]),
    N("engineering_disasters", "Desastres de Engenharia & Aviação", "science",
      "Reconstituição de acidentes: aviação, pontes, barragens, falhas de sistemas.",
      (4, 8), (0.05, 0.15), 50, 92, 70, 70, 40, 30, 75,
      ["stock_narrated", "ai_images_narrated", "clip_commentary"], "Homens 25-54, engenheiros, EUA/UK/DE",
      ["Acidentes aéreos", "Estruturas que falharam", "Erros de 1 segundo"],
      ["plane crash", "air crash investigation", "engineering disaster", "bridge collapse", "dam failure"],
      ["The 11 seconds that doomed flight {X}", "One tiny bolt brought this bridge down"],
      ["aviation", "CatastrophicFailure"], []),
    N("luxury_billionaires", "Vidas de Bilionários & Luxo", "money",
      "Como gastam, o que possuem, excessos e segredos dos ultra-ricos.",
      (4, 9), (0.06, 0.2), 80, 70, 80, 75, 30, 15, 40,
      ["stock_narrated", "ai_images_narrated", "clip_commentary"], "18-34, aspiracional, EN global",
      ["Posses absurdas", "Rotinas", "Excessos", "Heranças"],
      ["billionaire", "luxury lifestyle", "mega yacht", "richest", "how rich people spend"],
      ["Inside the $500M life of {X}", "Things only billionaires can buy"],
      ["LuxuryLifestyle"], []),
    N("legal_court", "Tribunal & Casos Jurídicos", "crime",
      "Julgamentos virais, reações em tribunal, advogados vs. réus arrogantes.",
      (5, 12), (0.06, 0.2), 55, 65, 85, 50, 70, 45, 50,
      ["clip_commentary", "stock_narrated"], "25-54, EUA",
      ["Réus arrogantes", "Juízes lendários", "Viradas em julgamento"],
      ["court case", "judge", "courtroom", "sentencing", "lawyer reacts"],
      ["He laughed at the judge — big mistake"], ["legaladvice"], []),
    N("health_body", "Corpo Humano & Saúde (explicativo)", "health",
      "O que acontece ao corpo quando... Ciência do corpo, sem aconselhamento médico.",
      (4, 10), (0.05, 0.15), 70, 88, 80, 85, 20, 55, 55,
      ["ai_images_narrated", "stock_narrated"], "25-54, EUA/UK",
      ["E se fizesses X", "Sinais do corpo", "Mitos"],
      ["what happens to your body", "human body facts", "sleep science", "fasting"],
      ["What happens to your body if you stop eating sugar for 30 days"], ["science"], []),
    N("survival_scenarios", "Sobrevivência & Cenários Extremos", "world",
      "Como sobreviver a..., cenários extremos, 'e se' catastróficos.",
      (3, 6.5), (0.05, 0.15), 55, 85, 85, 90, 15, 20, 45,
      ["ai_images_narrated", "ai_video_full", "stock_narrated"], "Homens 16-44, EN global",
      ["E se...", "Como sobreviver", "Situações extremas"],
      ["how to survive", "what if", "survival", "worst case scenario"],
      ["How long would you survive if {X}", "What if the internet disappeared tomorrow"],
      ["preppers", "Survival"], []),
    N("ancient_civilizations", "Civilizações Antigas & Arqueologia", "history",
      "Descobertas arqueológicas, tecnologia perdida, civilizações apagadas.",
      (3, 6.5), (0.04, 0.12), 60, 92, 75, 90, 25, 10, 55,
      ["ai_images_narrated", "stock_narrated"], "Homens 25-54, EUA/UK/AU",
      ["Descobertas recentes", "Tecnologia perdida", "Cidades perdidas"],
      ["ancient civilization", "archaeology", "lost city", "ancient technology", "pyramids"],
      ["Archaeologists found something under the pyramids"], ["ArtefactPorn", "archaeology"],
      ["Göbekli_Tepe", "Antikythera_mechanism"]),
    N("reddit_stories", "Histórias do Reddit (AITA/revenge)", "stories",
      "Histórias de conflito/drama narradas sobre gameplay. Volume alto, RPM baixo.",
      (1.2, 3), (0.02, 0.06), 95, 40, 90, 70, 10, 30, 10,
      ["text_story"], "13-24, EUA",
      ["Vingança", "AITA", "Família tóxica", "Traições"],
      ["reddit stories", "aita", "revenge story", "entitled parents"],
      ["My sister stole my wedding date, so I..."],
      ["AmItheAsshole", "pettyrevenge", "ProRevenge", "entitledparents"], []),
    N("movie_tv_explained", "Filmes & Séries Explicados", "entertainment",
      "Finais explicados, teorias, detalhes escondidos. Alto risco de Content ID em recortes.",
      (2, 5), (0.03, 0.1), 85, 55, 85, 40, 60, 60, 45,
      ["clip_commentary", "ai_images_narrated"], "16-34, EN global",
      ["Finais explicados", "Detalhes ocultos", "Teorias"],
      ["ending explained", "hidden details", "movie theory", "series recap"],
      ["You missed this detail in {X}"], ["movies", "FanTheories"], []),
    N("cars_machines", "Máquinas & Carros Extremos", "tech",
      "Engenharia de máquinas gigantes, supercarros, motores, tecnologia militar civil.",
      (4, 8), (0.05, 0.15), 60, 80, 80, 75, 45, 10, 45,
      ["stock_narrated", "clip_commentary", "ai_images_narrated"], "Homens 18-54, EUA/DE/UK",
      ["Máquinas gigantes", "Como funciona", "Recordes"],
      ["how it works", "biggest machine", "engine", "supercar", "mega machines"],
      ["The machine that eats mountains"], ["Engineering", "cars"], []),
    N("animals_nature_dark", "Natureza Cruel & Predadores", "nature",
      "Predadores, parasitas, animais mais perigosos — ciência da natureza extrema.",
      (2, 5), (0.03, 0.1), 65, 85, 90, 85, 45, 25, 35,
      ["stock_narrated", "ai_images_narrated", "clip_commentary"], "Mistura 16-44, EN global",
      ["Predadores", "Parasitas", "Animais mortais"],
      ["dangerous animals", "predator", "parasite", "deadliest animal"],
      ["This parasite controls its host's brain"], ["natureismetal", "HumansAreMetal"], []),
    N("real_estate_housing", "Imobiliário & Crise da Habitação", "money",
      "Mercado imobiliário, crise da habitação, cidades fantasma, investimento.",
      (9, 20), (0.1, 0.3), 55, 70, 55, 70, 20, 20, 60,
      ["stock_narrated", "ai_images_narrated"], "25-54, EUA/CA/AU/UK",
      ["Crise da habitação", "Cidades fantasma", "Investimento"],
      ["housing market", "real estate crash", "ghost city", "mortgage rates"],
      ["The housing crash nobody is ready for"], ["RealEstate", "REBubble"], []),
    N("crypto_markets", "Cripto & Mercados (drama)", "money",
      "Crashes, golpes e figuras do cripto. RPM alto mas volátil e YMYL.",
      (6, 14), (0.08, 0.25), 80, 40, 70, 80, 30, 55, 50,
      ["ai_images_narrated", "stock_narrated"], "Homens 18-44, EN global",
      ["Golpes", "Crashes", "Figuras polémicas"],
      ["crypto crash", "bitcoin", "crypto scam", "rug pull"],
      ["How this crypto founder vanished with $4B"], ["CryptoCurrency"], []),
    N("facts_top10", "Factos & Top 10 Bizarros", "entertainment",
      "Listas rápidas de factos estranhos — ótimo para Shorts em volume.",
      (1.5, 4), (0.03, 0.08), 95, 60, 90, 90, 20, 15, 20,
      ["ai_images_narrated", "stock_narrated", "text_story"], "13-34, EN global",
      ["Factos estranhos", "Listas"], ["weird facts", "top 10", "did you know"],
      ["You've been doing this wrong your whole life"], ["todayilearned"], []),
]

NICHE_BY_KEY = {n["key"]: n for n in NICHES}


def get_niche(key: str) -> dict | None:
    return NICHE_BY_KEY.get(key)
